import blurMap from "@/content/blur-placeholders.json";

const blurs = blurMap as Record<string, string>;

/**
 * Blur placeholder for an image in `public/work/`, keyed by its public path.
 *
 * The map is generated by `scripts/optimize-media.mjs`, so placeholders are
 * looked up here rather than duplicated into every entry in `projects.ts`.
 * Returns undefined for images the pipeline has not processed, which lets
 * `next/image` fall back to no placeholder instead of throwing.
 */
export function getBlur(src: string): string | undefined {
  return blurs[src];
}
