import type { Project } from "@/lib/types";

/**
 * Bootstrapped from the recovered Netlify site, then hand-maintained.
 * Media paths point at optimized output produced by scripts/optimize-media.mjs
 * from scripts/media-manifest.json. Run that script before the images resolve.
 *
 * Every alt string still marked "TODO:" needs a human pass - see TASKS.md.
 */
export const projects: Project[] = [
  {
    slug: "mercedes-actros-vr",
    title: "Mercedes-Benz Actros — PC VR Showroom",
    tagline: "High-fidelity VR truck configurator built in Unreal Engine 5.",
    client: "Mercedes-Benz",
    studio: "Agência DADS",
    year: "2026",
    platform: "PC VR (Unreal Engine 5)",
    role: "Senior Game Engineer — technical architecture, rendering, asset pipeline",
    disciplines: ["engine", "technical-art"],
    stack: ["Unreal Engine 5", "C++", "Blueprints", "VR", "Lumen", "Nanite", "Blender"],
    summary:
      "A high-fidelity PC VR showroom that lets a viewer stand inside an Actros and reconfigure it in real time. A server-driven configurator UI switches cabin, chassis, lighting and trailer variants without leaving the scene.",
    constraint:
      "Source CAD arrived as raw 14-15M triangle meshes with hundreds of unmanaged materials, against a stereo VR frame budget and a fixed texture streaming pool.",
    contribution: [
      "Rebuilt the CAD-to-engine pipeline: decimation, retopology, material consolidation and streaming budget management.",
      "Modified the Unreal shader and mesh importer to remove the UE5 normal recast so Blender and UE5 shading match exactly.",
      "Resolved virtual shadow map overflow, Lumen artifacts, streaming pool exhaustion and DLSS/Streamline plugin conflicts in stereo.",
      "Owned the UE 5.5 to 5.7 migration and revalidated lighting, materials and performance.",
    ],
    outcome: "In production.",
    cover: {
      kind: "image",
      src: "/work/mercedes-actros-vr/cover.avif",
      alt: "TODO: cover image pending - no asset recovered for this project",
      width: 1600,
      height: 900,
    },
    media: [
    ],
    featured: true,
    draft: true,
  },
  {
    slug: "cusutools",
    title: "CusuTools — Blender Addons",
    tagline: "Commercial pipeline tooling for 3D artists: TexelPack and PreflightKit.",
    client: "Independent product",
    studio: "CusuTools",
    year: "2026",
    platform: "Blender (Python / bpy)",
    role: "Founder, developer, support",
    disciplines: ["tooling"],
    stack: ["Python", "bpy", "Blender"],
    summary:
      "Two commercial Blender addons sold on Superhive Market. TexelPack handles UV packing and texel density normalization, including exporting the texel density map as an image for layout inspection. PreflightKit validates and exports game-ready assets, catching pipeline errors before they reach an engine.",
    constraint:
      "Shipping software to strangers means the failure modes are theirs, not yours - scenes you will never see, Blender versions you did not test.",
    contribution: [
      "Full product cycle: market research, development, release, support and updates.",
      "Storefront, pricing, refunds, and affiliate and creator outreach.",
    ],
    outcome: "Both addons released and in active use.",
    cover: {
      kind: "image",
      src: "/work/cusutools/cover.avif",
      alt: "TODO: cover image pending - no asset recovered for this project",
      width: 1600,
      height: 900,
    },
    media: [
    ],
    featured: true,
    draft: true,
  },
  {
    slug: "chevrolet-configurator",
    title: "Chevrolet — Web 3D Vehicle Configurator",
    tagline: "Real-time car customization in the browser with Three.js and WebGL.",
    client: "Chevrolet",
    studio: "Freelance",
    year: "2023-2024",
    platform: "Web (Three.js / WebGL)",
    role: "Freelance Web 3D Developer",
    disciplines: ["web-3d"],
    stack: ["Three.js", "WebGL", "JavaScript"],
    summary:
      "An interactive web platform for vehicle visualization, letting users change colors, wheels and components and see the result immediately.",
    constraint:
      "A browser 3D experience that had to stay smooth on desktop and mid-range mobile, with no install and no loading screen worth complaining about.",
    contribution: [
      "Built the real-time customization system across colors, wheels and components.",
      "Optimized the rendering path for consistent framerate across desktop and mobile.",
      "Iterated with design and product against client feedback.",
    ],
    outcome: "Delivered.",
    cover: {
      kind: "image",
      src: "/work/chevrolet-configurator/cover.avif",
      alt: "TODO: cover image pending - no asset recovered for this project",
      width: 1600,
      height: 900,
    },
    media: [
    ],
    featured: true,
    draft: true,
  },
  {
    slug: "ohbb-raid",
    title: "OHBB Raid — Environment, Monster & Materials",
    tagline: "Environment art, a hand-painted ice monster, and Substance Designer materials.",
    client: "Oh Baby Games",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist / Technical Artist",
    disciplines: ["3d-art", "technical-art"],
    stack: ["Blender", "Substance Designer", "Substance Painter", "Unity"],
    summary:
      "The largest art contribution on OHBB Raid: environment modeling and texturing, a hand-painted ice monster, and a set of tileable materials authored procedurally in Substance Designer.",
    constraint:
      "A tiling material set had to cover a whole environment on a mobile texture budget while still varying enough to avoid visible repetition.",
    contribution: [
      "Modeled, unwrapped and textured the environment.",
      "Hand-painted the Head Ice monster's textures.",
      "Authored carpet, floor and marble materials procedurally in Substance Designer.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-raid/01-0-1.avif",
      alt: "TODO: 0 1",
      width: 1916,
      height: 880,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-raid/02-0-3.avif",
        alt: "TODO: 0 3",
        width: 1916,
        height: 882,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/03-0.avif",
        alt: "TODO: 0",
        width: 1916,
        height: 880,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/04-1.avif",
        alt: "TODO: 1",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/05-2.avif",
        alt: "TODO: 2",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/06-3.avif",
        alt: "TODO: 3",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/07-4.avif",
        alt: "TODO: 4",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/08-5.avif",
        alt: "TODO: 5",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/09-6.avif",
        alt: "TODO: 6",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/10-7.avif",
        alt: "TODO: 7",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/11-8.avif",
        alt: "TODO: 8",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/12-0.avif",
        alt: "TODO: 0",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/13-1.avif",
        alt: "TODO: 1",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/14-2.avif",
        alt: "TODO: 2",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/15-0.avif",
        alt: "TODO: 0",
        width: 2048,
        height: 2048,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/16-carpet-material.avif",
        alt: "TODO: carpet material",
        width: 1920,
        height: 1004,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/17-carpet-material-alt.avif",
        alt: "TODO: carpet material alt",
        width: 1920,
        height: 1004,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/18-floor-material.avif",
        alt: "TODO: floor material",
        width: 1920,
        height: 1004,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/19-marble-material.avif",
        alt: "TODO: marble material",
        width: 1308,
        height: 901,
      },
    ],
    featured: true,
  },
  {
    slug: "ohbb-kart-spongebob",
    title: "SpongeBob Kart — Bikini Bottom",
    tagline: "Environment and character art for a licensed mobile kart racer.",
    client: "SpongeBob SquarePants (Nickelodeon)",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist / Developer",
    disciplines: ["3d-art"],
    stack: ["Unity", "Blender", "Substance Painter", "C#"],
    summary:
      "Modeling, UVs and textures for the SpongeBob environment and characters in OHBB Kart - Bikini Bottom houses, props and cast, built to read clearly at racing speed on a phone.",
    constraint:
      "Licensed-IP fidelity on a mobile budget: recognizable silhouettes at 60fps on mid-range devices.",
    contribution: [
      "Modeled and textured environment sets and hero props.",
      "Built characters to the licensor's model sheets.",
      "Optimized meshes and materials against the mobile draw-call budget.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-kart-spongebob/01-secret-map.avif",
      alt: "TODO: secret map",
      width: 812,
      height: 408,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/02-spongebob.avif",
        alt: "TODO: spongebob",
        width: 1920,
        height: 1256,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/03-squidward.avif",
        alt: "TODO: squidward",
        width: 1920,
        height: 1256,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/04-pineapple-house.avif",
        alt: "TODO: pineapple house",
        width: 1920,
        height: 1256,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/05-bikini-bottom-houses.avif",
        alt: "TODO: bikini bottom houses",
        width: 1920,
        height: 1080,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/06-patrick.avif",
        alt: "TODO: patrick",
        width: 1920,
        height: 1256,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/07-plankton-lab.avif",
        alt: "TODO: plankton lab",
        width: 1920,
        height: 1256,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/08-plankton-lab-detail.avif",
        alt: "TODO: plankton lab detail",
        width: 1920,
        height: 1080,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/09-sandy.avif",
        alt: "TODO: sandy",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/10-plankton-character.avif",
        alt: "TODO: plankton character",
        width: 3483,
        height: 2160,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/11-plankton.avif",
        alt: "TODO: plankton",
        width: 1280,
        height: 715,
      },
    ],
    featured: true,
  },
  {
    slug: "ohbb-kart-invader-zim",
    title: "Invader Zim Kart — Environment",
    tagline: "Full environment set for the Invader Zim track.",
    client: "Invader Zim (Nickelodeon)",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist / Developer",
    disciplines: ["3d-art"],
    stack: ["Unity", "Blender", "Substance Painter"],
    summary:
      "Modeling, UVs and textures for the Invader Zim environment in OHBB Kart, including Zim's house, the Voot Cruiser and the surrounding street set.",
    constraint:
      "Translating a flat, graphic 2D art style into 3D without losing the angular, off-kilter shape language the show is built on.",
    contribution: [
      "Modeled and textured the full environment set.",
      "Built the hero props: Zim's house and the Voot Cruiser.",
      "Kept the asset lineup consistent in scale and material response across the track.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-kart-invader-zim/01-invader-zim-key-art.avif",
      alt: "TODO: invader zim key art",
      width: 1913,
      height: 881,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/02-10.avif",
        alt: "TODO: 10",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/03-2.avif",
        alt: "TODO: 2",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/04-3.avif",
        alt: "TODO: 3",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/05-4.avif",
        alt: "TODO: 4",
        width: 1920,
        height: 1110,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/06-5.avif",
        alt: "TODO: 5",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/07-6.avif",
        alt: "TODO: 6",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/08-7.avif",
        alt: "TODO: 7",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/09-8.avif",
        alt: "TODO: 8",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/10-9.avif",
        alt: "TODO: 9",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/11-zim-house.avif",
        alt: "TODO: zim house",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/12-environment.avif",
        alt: "TODO: environment",
        width: 1913,
        height: 881,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/13-asset-lineup.avif",
        alt: "TODO: asset lineup",
        width: 1920,
        height: 1256,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/14-voot-cruiser.avif",
        alt: "TODO: voot cruiser",
        width: 1920,
        height: 1080,
      },
    ],
    featured: true,
  },
  {
    slug: "historias-para-armar",
    title: "Historias Para Armar — Disney",
    tagline: "Art direction and Unity WebGL for a Disney educational platform.",
    client: "Disney",
    studio: "DIGI Learnnials",
    year: "2020-2021",
    platform: "Web (Unity WebGL)",
    role: "Lead Artist, Art Director & Unity Developer",
    disciplines: ["art-direction", "web-3d"],
    stack: ["Unity", "C#", "WebGL"],
    summary:
      "An educational platform built for Disney where students aged 8 to 11 build narrative arcs in an interactive scene and character editor.",
    constraint:
      "One visual language had to hold up across culturally diverse characters, made by six different artists, and still satisfy Disney and a panel of educational experts.",
    contribution: [
      "Directed a team of 6 artists on character design and visual assets.",
      "Built the scene and character editor in C#.",
      "Implemented a teacher dashboard and activity creation tools for classroom use.",
      "Established the art style and the production pipeline that kept it consistent.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/historias-para-armar/01-0.avif",
      alt: "TODO: 0",
      width: 1280,
      height: 720,
    },
    media: [
    ],
    featured: true,
  },
  {
    slug: "peakmines",
    title: "Peakmines — Art & Technical Direction",
    tagline: "Art direction, 2D and 3D production for an indie title.",
    client: "Peakmines",
    studio: "Inflextion Studios",
    year: "2021-2022",
    platform: "PC (Unity)",
    role: "Art Director & Unity Developer",
    disciplines: ["art-direction", "3d-art"],
    stack: ["Unity", "Blender", "Substance Painter", "Photoshop"],
    summary:
      "Art and technical direction on Peakmines, plus hands-on 2D and 3D production including the dwarf character set.",
    constraint:
      "Directing a multidisciplinary team while staying hands-on in production, and keeping the pipeline efficient enough for a small studio.",
    contribution: [
      "Set the art direction and established the asset pipeline.",
      "Modeled, unwrapped and textured the character set.",
      "Coordinated designers, developers and artists across the project lifecycle.",
    ],
    outcome: "Delivered.",
    cover: {
      kind: "image",
      src: "/work/peakmines/01-0.avif",
      alt: "TODO: 0",
      width: 3840,
      height: 2160,
    },
    media: [
      {
        kind: "image",
        src: "/work/peakmines/02-1.avif",
        alt: "TODO: 1",
        width: 3840,
        height: 2160,
      },
      {
        kind: "image",
        src: "/work/peakmines/03-2.avif",
        alt: "TODO: 2",
        width: 3840,
        height: 2014,
      },
      {
        kind: "image",
        src: "/work/peakmines/04-dwarf-01.avif",
        alt: "TODO: dwarf 01",
        width: 1080,
        height: 1080,
      },
      {
        kind: "image",
        src: "/work/peakmines/05-dwarf-02.avif",
        alt: "TODO: dwarf 02",
        width: 1080,
        height: 1080,
      },
      {
        kind: "image",
        src: "/work/peakmines/06-dwarf-02-alt.avif",
        alt: "TODO: dwarf 02 alt",
        width: 1080,
        height: 748,
      },
      {
        kind: "image",
        src: "/work/peakmines/07-dwarf-03.avif",
        alt: "TODO: dwarf 03",
        width: 1080,
        height: 1080,
      },
      {
        kind: "video",
        src: "/work/peakmines/08-dwarves-turntable.mp4",
        alt: "TODO: dwarves turntable",
        width: 1920,
        height: 1080,
      },
    ],
    featured: false,
  },
  {
    slug: "ohbb-kart-tower-of-god",
    title: "Tower of God Kart — Characters",
    tagline: "Rak, Baam and Ha-Yuri modeled, unwrapped and textured.",
    client: "Tower of God",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist",
    disciplines: ["3d-art"],
    stack: ["Blender", "Substance Painter", "Unity"],
    summary:
      "Character work for the Tower of God roster in OHBB Kart: modeling, UVs and textures for Rak, Baam and Ha-Yuri.",
    constraint:
      "Three characters with very different proportions had to sit in the same kart rig and read at the same distance.",
    contribution: [
      "Modeled and unwrapped each character.",
      "Textured to match the source illustration style.",
      "Iterated on proportions through several WIP passes against licensor feedback.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-kart-tower-of-god/01-character-wip.avif",
      alt: "TODO: character wip",
      width: 2825,
      height: 1920,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/02-baam-final.avif",
        alt: "TODO: baam final",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/03-wip.avif",
        alt: "TODO: wip",
        width: 3840,
        height: 2160,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/04-wip-2.avif",
        alt: "TODO: wip 2",
        width: 3840,
        height: 2160,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/05-wip-9.avif",
        alt: "TODO: wip 9",
        width: 3840,
        height: 2160,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/06-wip-10.avif",
        alt: "TODO: wip 10",
        width: 3840,
        height: 2160,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/07-rak-final.avif",
        alt: "TODO: rak final",
        width: 4408,
        height: 1584,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/08-tower-of-god-key-art.avif",
        alt: "TODO: tower of god key art",
        width: 1280,
        height: 720,
      },
    ],
    featured: false,
  },
  {
    slug: "ohbb-kart-characters",
    title: "OHBB Kart — Original Characters",
    tagline: "Original character work outside the licensed roster.",
    client: "Oh Baby Games",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist",
    disciplines: ["3d-art"],
    stack: ["Blender", "Substance Painter", "ZBrush", "Unity"],
    summary:
      "Original characters designed and built for OHBB Kart, covering modeling, UVs and textures.",
    constraint:
      "Original designs still had to sit alongside licensed IP characters without looking like they came from a different game.",
    contribution: [
      "Modeled, unwrapped and textured each character.",
      "Matched the established roster's proportions and material language.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-kart-characters/01-0.avif",
      alt: "TODO: 0",
      width: 3840,
      height: 3840,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/02-1.avif",
        alt: "TODO: 1",
        width: 3840,
        height: 3840,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/03-2.avif",
        alt: "TODO: 2",
        width: 3840,
        height: 3840,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/04-3.avif",
        alt: "TODO: 3",
        width: 3840,
        height: 3840,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/05-0.avif",
        alt: "TODO: 0",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/06-1.avif",
        alt: "TODO: 1",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/07-2.avif",
        alt: "TODO: 2",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/08-3.avif",
        alt: "TODO: 3",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/09-4.avif",
        alt: "TODO: 4",
        width: 1920,
        height: 1920,
      },
    ],
    featured: false,
  },
  {
    slug: "tower-defense-props",
    title: "Tower Defense — Prop Library",
    tagline: "A full prop library built for a tower defense prototype.",
    client: "Oh Baby Games",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist",
    disciplines: ["3d-art"],
    stack: ["Blender", "Substance Painter", "Unity"],
    summary:
      "Modeling, UVs and textures for the prop library of a tower defense prototype - towers, structures and set dressing built as a consistent kit.",
    constraint:
      "Props had to be readable from a fixed top-down camera at small on-screen size, and reusable across many level layouts.",
    contribution: [
      "Built the prop kit to a shared scale and material set.",
      "Optimized for instancing across dense levels.",
    ],
    outcome: "Prototype delivered.",
    cover: {
      kind: "image",
      src: "/work/tower-defense-props/01-0.avif",
      alt: "TODO: 0",
      width: 1920,
      height: 1920,
    },
    media: [
      {
        kind: "image",
        src: "/work/tower-defense-props/02-1.avif",
        alt: "TODO: 1",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/03-10.avif",
        alt: "TODO: 10",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/04-11.avif",
        alt: "TODO: 11",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/05-12.avif",
        alt: "TODO: 12",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/06-13.avif",
        alt: "TODO: 13",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/07-2.avif",
        alt: "TODO: 2",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/08-3-1.avif",
        alt: "TODO: 3 1",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/09-3.avif",
        alt: "TODO: 3",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/10-4.avif",
        alt: "TODO: 4",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/11-5.avif",
        alt: "TODO: 5",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/12-6.avif",
        alt: "TODO: 6",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/13-7.avif",
        alt: "TODO: 7",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/14-8.avif",
        alt: "TODO: 8",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/15-9.avif",
        alt: "TODO: 9",
        width: 1920,
        height: 1920,
      },
    ],
    featured: false,
  },
  {
    slug: "weapons-props",
    title: "Weapon Set — Game-Ready Props",
    tagline: "Four game-ready weapons: pistol, shotgun, rifle, rocket launcher.",
    client: "Oh Baby Games",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist",
    disciplines: ["3d-art"],
    stack: ["Blender", "Substance Painter"],
    summary:
      "A set of game-ready weapon props: modeling, UVs and PBR texturing, built to a shared texel density and material set.",
    constraint:
      "Four silhouettes that had to stay distinguishable at thumbnail size in a weapon-select UI.",
    contribution: [
      "Modeled and unwrapped each weapon.",
      "Textured to a shared PBR material library.",
    ],
    outcome: "Prototype delivered.",
    cover: {
      kind: "image",
      src: "/work/weapons-props/01-shotgun.avif",
      alt: "TODO: shotgun",
      width: 1920,
      height: 1920,
    },
    media: [
      {
        kind: "image",
        src: "/work/weapons-props/02-pistol.avif",
        alt: "TODO: pistol",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/weapons-props/03-rifle.avif",
        alt: "TODO: rifle",
        width: 1920,
        height: 1920,
      },
      {
        kind: "image",
        src: "/work/weapons-props/04-rocket-launcher.avif",
        alt: "TODO: rocket launcher",
        width: 1920,
        height: 1920,
      },
    ],
    featured: false,
  },
];

export const featuredProjects = projects.filter((p) => p.featured && !p.draft);
export const publishedProjects = projects.filter((p) => !p.draft);

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}
