import type { Project } from "@/lib/types";

/**
 * Bootstrapped from the recovered Netlify site, then hand-maintained.
 * Media paths point at optimized output produced by scripts/optimize-media.mjs
 * from scripts/media-manifest.json. Run that script before the images resolve.
 *
 * Alt text is written from the images themselves, not from filenames.
 * Publication restrictions per project live in docs/CONTENT.md. Read it
 * before adding any image to a project whose visuals are withheld.
 */
export const projects: Project[] = [
  {
    slug: "mercedes-actros-vr",
    title: "Mercedes-Benz Actros VR Showroom",
    tagline: "High-fidelity VR truck configurator built in Unreal Engine 5.",
    metaDescription:
      "PC VR showroom for the Mercedes-Benz Actros in Unreal Engine 5, rebuilding a 15M triangle CAD pipeline and fixing stereo VR rendering at engine level.",
    client: "Mercedes-Benz",
    studio: "Agência DADS",
    year: "2026",
    platform: "PC VR (Unreal Engine 5)",
    role: "Senior Game Engineer, owning technical architecture, rendering and the asset pipeline",
    disciplines: ["engine", "technical-art"],
    stack: ["Unreal Engine 5", "C++", "Blueprints", "VR", "Lumen", "Nanite", "Blender"],
    summary:
      "A high-fidelity PC VR showroom that lets a viewer stand inside an Actros and reconfigure it in real time. A server-driven configurator UI switches cabin, chassis, lighting and trailer variants without leaving the scene.",
    constraint:
      "Source CAD arrived as raw 14-15M triangle meshes with hundreds of unmanaged materials, against a stereo VR frame budget and a fixed texture streaming pool.",
    contribution: [
      "Rebuilt the CAD-to-engine pipeline: decimation, retopology, material consolidation and streaming budget management.",
      "Modified the Unreal shader and mesh importer to remove the UE5 normal recast so Blender and UE5 shading match exactly.",
      "Resolved virtual shadow map overflow, Lumen artifacts, streaming pool exhaustion and DLSS/Streamline plugin conflicts in stereo.",
      "Owned the UE 5.5 to 5.7 migration and revalidated lighting, materials and performance.",
    ],
    outcome: "In production.",
    // CLEARED IMAGERY: exactly these two renders, approved 2026-08-26. The
    // project is still unreleased. Do not add another Mercedes-Benz image here
    // without Cusu confirming clearance for that specific asset. See the
    // restrictions table in docs/CONTENT.md.
    cover: {
      kind: "image",
      src: "/work/mercedes-actros-vr/01-exterior.avif",
      alt: "The Mercedes-Benz Actros 2653 tractor unit in blue, coupled to a silver box trailer, parked in the dark showroom environment with reflections running along the polished floor.",
      width: 1877,
      height: 789,
    },
    media: [
      {
        kind: "image",
        src: "/work/mercedes-actros-vr/02-cabin.avif",
        alt: "Interior of the Actros cabin seen from behind the seats: the steering wheel with the Mercedes-Benz star, the instrument and infotainment screens, and the tan upper dash sweeping across to the passenger side.",
        width: 1600,
        height: 673,
      },
    ],
    visuals: { status: "public" },
    featured: true,
  },
  {
    slug: "cusutools",
    title: "CusuTools Blender Addons",
    tagline: "Commercial pipeline tooling for 3D artists. TexelPack is out; PreflightKit is in development.",
    metaDescription:
      "TexelPack and PreflightKit, Blender addons built as products: UV packing, texel density normalization and game-ready asset validation, sold and supported.",
    client: "Independent product",
    studio: "CusuTools",
    year: "2026",
    platform: "Blender (Python / bpy)",
    role: "Founder, developer, support",
    disciplines: ["tooling"],
    stack: ["Python", "bpy", "Blender 3.6 LTS / 4.x / 5.x"],
    summary:
      "Blender addons built and sold as products. TexelPack, released on Superhive Market, packs UV islands into a tight atlas, holds texel density consistent across a whole selection, and draws the result as a viewport overlay so wasted space and stretching are visible before a bake. PreflightKit, in development, validates and exports game-ready assets to catch pipeline errors before they reach an engine.",
    constraint:
      "Shipping software to strangers means the failure modes are theirs, not yours. They happen in scenes you will never see, on Blender versions you did not test. TexelPack runs on Blender's bundled Python with zero external dependencies for exactly that reason: nothing to pip-install, nothing to break in someone else's environment.",
    contribution: [
      "Four packing algorithms: MAXRECTS, Guillotine, Shelf, and a Max Quality mode that packs by real island shape so small pieces fill concavities.",
      "Texel density normalized against each object's real 3D surface area, object scale included, with a color-coded viewport overlay grading every face against the target.",
      "Vectorized island extraction: 100k polygons in under a second, with pixel-exact ±1px padding for clean bake bleeding.",
      "UDIM and group packing, mirrored-island stacking, reserved atlas regions, presets, and JSON / CSV / SVG layout export for Substance and Photoshop.",
      "Full product cycle, from market research through development, release, support and updates, plus storefront, pricing, refunds and creator outreach.",
    ],
    outcome: "TexelPack is released and in active use, under GPL-3.0-or-later. PreflightKit is in development.",
    cover: {
      kind: "image",
      src: "/work/cusutools/01-before-after.avif",
      alt: "TexelPack product banner comparing the same crate asset before and after packing: broken UVs and inconsistent texel density on the left, a clean even checker pattern on the right.",
      width: 1672,
      height: 941,
    },
    media: [
      {
        kind: "image",
        src: "/work/cusutools/02-density-overlay.avif",
        alt: "The crate asset in the Blender viewport under TexelPack's texel density overlay, faces graded from yellow to orange against the target resolution.",
        width: 720,
        height: 406,
        caption: "Texel density overlay grading every face against the target resolution.",
      },
      {
        kind: "image",
        src: "/work/cusutools/03-island-colors.avif",
        alt: "The same asset with each UV island shaded a different color, so island boundaries and their distribution across the mesh are visible at a glance.",
        width: 720,
        height: 406,
        caption: "Per-island color coding, showing how the atlas maps back onto the mesh.",
      },
      {
        kind: "image",
        src: "/work/cusutools/04-packed-result.avif",
        alt: "Blender split between the UV editor showing a packed atlas and the 3D viewport showing the crate with an even checker texture applied.",
        width: 720,
        height: 406,
        caption: "Packed atlas and the resulting checker pass, side by side.",
      },
      {
        kind: "image",
        src: "/work/cusutools/05-panel-islands.avif",
        alt: "TexelPack's island tools panel in Blender: stack, unstack, flip X and Y, straighten and rectify islands, with a similarity tolerance slider and selection helpers.",
        width: 552,
        height: 343,
      },
      {
        kind: "image",
        src: "/work/cusutools/06-panel-align.avif",
        alt: "TexelPack's align panel with horizontal and vertical distribute and orient controls for selected UV islands.",
        width: 538,
        height: 303,
      },
      {
        kind: "image",
        src: "/work/cusutools/07-panel-presets.avif",
        alt: "TexelPack's presets panel listing the Max Quality, Game Asset and Fast built-in configurations plus a field for saving a custom preset.",
        width: 541,
        height: 297,
      },
      {
        kind: "image",
        src: "/work/cusutools/08-panel-export.avif",
        alt: "TexelPack's statistics and export panel reporting 61.5 percent efficiency, 230 of 230 islands packed across 9 objects in 1643 milliseconds with zero overlaps, above SVG layout and JSON or CSV data export buttons.",
        width: 538,
        height: 720,
        caption:
          "Efficiency measured on real island geometry, not bounding boxes, with geometric overlap detection.",
      },
    ],
    video: {
      provider: "youtube",
      id: "v3WAIJE_sD8",
      title: "TexelPack for Blender: Perfect UV Packing and Texel Density in One Click",
      poster: "/work/cusutools/09-video-poster.avif",
      posterWidth: 1280,
      posterHeight: 720,
    },
    visuals: { status: "public" },
    links: [
      { label: "TexelPack", href: "https://texelpack.vercel.app/" },
      { label: "Buy on Superhive Market", href: "https://superhivemarket.com/products/texelpack" },
      { label: "Documentation", href: "https://texelpack.vercel.app/docs/index.html" },
    ],
    featured: true,
  },
  {
    slug: "chevrolet-configurator",
    title: "Chevrolet Web 3D Vehicle Configurator",
    tagline: "Real-time car customization in the browser with Three.js and WebGL.",
    metaDescription:
      "Interactive web 3D vehicle configurator for Chevrolet in Three.js and WebGL, with real-time colour, wheel and component changes on desktop and mobile.",
    client: "Chevrolet",
    studio: "Freelance",
    year: "2023-2024",
    platform: "Web (Three.js / WebGL)",
    role: "Freelance Web 3D Developer",
    disciplines: ["web-3d"],
    stack: ["Three.js", "WebGL", "JavaScript"],
    summary:
      "An interactive web platform for vehicle visualization, letting users change colors, wheels and components and see the result immediately.",
    constraint:
      "A browser 3D experience that had to stay smooth on desktop and mid-range mobile, with no install and no loading screen worth complaining about.",
    contribution: [
      "Built the real-time customization system across colors, wheels and components.",
      "Optimized the rendering path for consistent framerate across desktop and mobile.",
      "Iterated with design and product against client feedback.",
    ],
    outcome: "Delivered.",
    media: [],
    visuals: {
      status: "withheld",
      reason: "Client contract. The work can be described but not shown.",
    },
    featured: true,
  },
  {
    slug: "ohbb-raid",
    title: "OHBB Raid Environment, Monster and Materials",
    tagline: "Environment art, a hand-painted ice monster, Substance Designer materials, and the map itself.",
    metaDescription:
      "Environment art, a hand-painted ice monster, procedural Substance Designer materials and Unity map programming for OHBB Raid, a mobile Oh Baby Games title.",
    client: "Oh Baby Games",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist, Technical Artist and Unity map programmer",
    disciplines: ["3d-art", "technical-art", "engine"],
    stack: ["Blender", "Substance Designer", "Substance Painter", "Unity", "C#"],
    summary:
      "The largest art contribution on OHBB Raid: environment modeling and texturing, a hand-painted ice monster, and a set of tileable materials authored procedurally in Substance Designer.",
    constraint:
      "A tiling material set had to cover a whole environment on a mobile texture budget while still varying enough to avoid visible repetition.",
    contribution: [
      "Modeled, unwrapped and textured the environment.",
      "Hand-painted the Head Ice monster's textures.",
      "Authored carpet, floor and marble materials procedurally in Substance Designer.",
      "Assembled and programmed the map in Unity: layout, collision and route logic.",
      "Wrote the C# gameplay systems for the map and set up its materials, shaders and scene lighting.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-raid/01-0-1.avif",
      alt: "Wide shot of the Raid environment: white stone platforms and arches holding glowing blue portals, above the sea, with orange-leaved trees on the cliffs.",
      width: 1916,
      height: 880,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-raid/02-0-3.avif",
        alt: "The Raid environment seen from the bridge, the long arched span running out toward the portals.",
        width: 1600,
        height: 737,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/03-0.avif",
        alt: "The full arched bridge curving between platforms under a bright sky, portals glowing at either end.",
        width: 1600,
        height: 735,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/04-1.avif",
        alt: "Ornate golden gateway prop crowned with spikes, isolated on grey.",
        width: 962,
        height: 1411,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/05-2.avif",
        alt: "Slim white and gold arch prop with blue inlays, isolated on grey.",
        width: 762,
        height: 1509,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/06-3.avif",
        alt: "Grey layered rock formation prop, isolated on grey.",
        width: 897,
        height: 1331,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/07-4.avif",
        alt: "Pedestal prop holding a glowing blue orb inside golden rings.",
        width: 769,
        height: 1026,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/08-5.avif",
        alt: "Carved stone pillar with a lit panel near the top and a decorated shaft.",
        width: 521,
        height: 1030,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/09-6.avif",
        alt: "Sci-fi supply crate with banded plating and glowing blue strips down its sides.",
        width: 1093,
        height: 814,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/10-7.avif",
        alt: "Tall slim banner pole in white and gold with a flared head.",
        width: 394,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/11-8.avif",
        alt: "Wide ceremonial gateway arch in white, gold and blue, isolated on grey.",
        width: 1209,
        height: 1491,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/12-0.avif",
        alt: "The Head Ice monster, a crystalline formation of pale blue shards fanned out like a mane.",
        width: 1067,
        height: 1541,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/13-1.avif",
        alt: "The Head Ice monster from a lower angle, showing the layered ice shards.",
        width: 1056,
        height: 1426,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/14-2.avif",
        alt: "The Head Ice monster in three-quarter view, its glowing face visible between the shards.",
        width: 1147,
        height: 1479,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/15-0.avif",
        alt: "The marble floor material previewed on a cube against an outdoor grassland backdrop.",
        width: 1483,
        height: 1460,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/16-carpet-material.avif",
        alt: "Substance Designer graph for the round red carpet, the node network laid out beside the rendered result.",
        width: 1600,
        height: 837,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/17-carpet-material-alt.avif",
        alt: "Substance Designer graph for the gold square carpet, with its node network trailing off to the right.",
        width: 1600,
        height: 837,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/18-floor-material.avif",
        alt: "Substance Designer graph for the marble floor tile, shown on a cube with the node network behind it.",
        width: 1600,
        height: 837,
      },
      {
        kind: "image",
        src: "/work/ohbb-raid/19-marble-material.avif",
        alt: "The marble material previewed on a sphere, showing the banding and surface sheen.",
        width: 1308,
        height: 901,
      },
    ],
    visuals: { status: "public" },
    featured: true,
  },
  {
    slug: "ohbb-kart-spongebob",
    title: "SpongeBob Kart, Bikini Bottom",
    tagline: "Texturing and Unity map programming for a licensed mobile kart racer.",
    metaDescription:
      "UV and texture work on the SpongeBob track for OHBB Kart, plus the Unity map programming: Bikini Bottom houses, props and cast running at 60fps on mobile.",
    client: "SpongeBob SquarePants (Nickelodeon)",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "Texture Artist and Unity map programmer",
    disciplines: ["3d-art", "engine"],
    stack: ["Unity", "C#", "Substance Painter", "Blender"],
    summary:
      "UVs and texturing for the SpongeBob environment and cast in OHBB Kart, plus the Unity work that turned those assets into a playable track: Bikini Bottom houses, props and characters built to read clearly at racing speed on a phone.",
    constraint:
      "Licensed-IP fidelity on a mobile budget. The silhouettes have to stay recognizable at 60fps on mid-range devices, and the track has to be readable at speed.",
    contribution: [
      "Unwrapped and textured the environment sets, hero props and characters. Modeling on this title was Steban Goca's.",
      "Assembled and programmed the map in Unity: layout, collision, track bounds and route logic.",
      "Wrote the C# gameplay systems for the map, covering triggers, checkpoints, obstacles and pickups.",
      "Set up the scene in Unity, including materials, shaders and atmospheric effects.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-kart-spongebob/01-secret-map.avif",
      alt: "In-game shot of the Chum Bucket at night on the kart track, its neon sign glowing red against the Bikini Bottom skyline and a striped lighthouse.",
      width: 812,
      height: 408,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/02-spongebob.avif",
        alt: "Four turnaround views of SpongeBob's pineapple house, textured with a woven rind pattern, porthole windows and green leaves on top.",
        width: 1600,
        height: 1047,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/03-squidward.avif",
        alt: "Four turnaround views of Squidward's house, the blue-grey moai head with a wooden door in its mouth.",
        width: 1600,
        height: 1047,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/04-pineapple-house.avif",
        alt: "Four turnaround views of a grey stacked-stone Bikini Bottom building with red antenna arms and porthole windows.",
        width: 1600,
        height: 1047,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/05-bikini-bottom-houses.avif",
        alt: "Presentation render of the three Bikini Bottom homes side by side: Patrick's rock dome, Squidward's moai head and SpongeBob's pineapple.",
        width: 1600,
        height: 900,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/06-patrick.avif",
        alt: "Four turnaround views of Patrick's rock dome home, a pitted red-brown hemisphere with a gold weather vane on top.",
        width: 1600,
        height: 1047,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/07-plankton-lab.avif",
        alt: "Four turnaround views of the Chum Bucket, a rusted metal bucket building with a curved handle and its painted sign.",
        width: 1600,
        height: 1047,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/08-plankton-lab-detail.avif",
        alt: "Interior of the Chum Bucket lit in sickly green, with the kitchen doors, an orders window and the menu board listing chum dishes.",
        width: 1600,
        height: 900,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/09-sandy.avif",
        alt: "Sandy Cheeks in her white spacesuit and glass helmet, shown front and three-quarter in a T-pose.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/10-plankton-character.avif",
        alt: "Four turnaround views of Plankton in a blue and orange captain's hat, with a single antenna and a mechanical lower body.",
        width: 1600,
        height: 992,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-spongebob/11-plankton.avif",
        alt: "Plankton's silhouette thrown across a lit doorway inside the Chum Bucket, arms raised, in teal and blue light.",
        width: 1280,
        height: 715,
      },
    ],
    visuals: { status: "public" },
    featured: true,
  },
  {
    slug: "ohbb-kart-invader-zim",
    title: "Invader Zim Kart Environment",
    tagline: "Texturing and Unity map programming for the Invader Zim track.",
    metaDescription:
      "Texturing and Unity map programming for the Invader Zim track in OHBB Kart, covering Zim's house, the Voot Cruiser and the full street set of assets.",
    client: "Invader Zim (Nickelodeon)",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "Texture Artist and Unity map programmer",
    disciplines: ["3d-art", "engine"],
    stack: ["Unity", "C#", "Substance Painter", "Blender"],
    summary:
      "UVs and texturing for the Invader Zim environment in OHBB Kart, including Zim's house, the Voot Cruiser and the surrounding street set, plus the Unity work that assembled and programmed the track.",
    constraint:
      "Translating a flat, graphic 2D style into 3D without losing the angular, off-kilter shape language the show is built on, then making that street work as a race track.",
    contribution: [
      "Unwrapped and textured the full environment set and its hero props. Modeling on this title was Steban Goca's.",
      "Assembled and programmed the map in Unity: layout, collision, track bounds and route logic.",
      "Wrote the C# gameplay systems for the map, covering triggers, checkpoints and obstacles.",
      "Set up the scene in Unity, including materials, shaders and the night-time atmospheric pass.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-kart-invader-zim/01-invader-zim-key-art.avif",
      alt: "Night street on the Invader Zim track, pink and purple houses with glowing windows under a swirling violet sky.",
      width: 1913,
      height: 881,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/02-10.avif",
        alt: "A pink two-storey corner building with graffiti and lit windows, isolated on black.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/03-2.avif",
        alt: "A magenta hovering machine with glowing pink lights and exhaust pipes, isolated on black.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/04-3.avif",
        alt: "Near-black shot of the track surface, a thin rim of light picking out its raised edge.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/05-4.avif",
        alt: "Skool interior with a teal checkered floor, graffiti scrawled on the blue walls and a glowing red window.",
        width: 1600,
        height: 925,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/06-5.avif",
        alt: "Interior prop set laid out together: lockers, a toilet, a waste bin, a fridge and a metal counter.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/07-6.avif",
        alt: "A dark purple house with a rounded roof and glowing cyan windows.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/08-7.avif",
        alt: "A purple tower house with a spire, a lightning rod and pink lit windows.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/09-8.avif",
        alt: "The Skool building with its sign, dark red walls, floodlights and two rows of green windows.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/10-9.avif",
        alt: "A pink apartment block with graffiti and a fire escape running down the front.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/11-zim-house.avif",
        alt: "Zim's house, a narrow teal and purple building with a steep roof and glowing pink windows.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/12-environment.avif",
        alt: "The assembled Invader Zim street at night, houses lit and the sky swirling overhead.",
        width: 1600,
        height: 737,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/13-asset-lineup.avif",
        alt: "Grid comparing reference stills from the show on the left against the finished 3D models on the right, covering houses, props and characters.",
        width: 1600,
        height: 1047,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-invader-zim/14-voot-cruiser.avif",
        alt: "Presentation render of the Voot Cruiser, the untextured grey model beside the finished red and pink textured version.",
        width: 1600,
        height: 900,
      },
    ],
    visuals: { status: "public" },
    featured: true,
  },
  {
    slug: "historias-para-armar",
    title: "Historias Para Armar for Disney",
    tagline: "Art direction and Unity WebGL for a Disney educational platform.",
    metaDescription:
      "Art direction and Unity WebGL development for Historias Para Armar, a Disney educational platform where children aged 8 to 11 build their own narratives.",
    client: "Disney",
    studio: "DIGI Learnnials",
    year: "2020-2021",
    platform: "Web (Unity WebGL)",
    role: "Lead Artist, Art Director & Unity Developer",
    disciplines: ["art-direction", "web-3d"],
    stack: ["Unity", "C#", "WebGL"],
    summary:
      "An educational platform built for Disney where students aged 8 to 11 build narrative arcs in an interactive scene and character editor.",
    constraint:
      "One visual language had to hold up across culturally diverse characters, made by six different artists, and still satisfy Disney and a panel of educational experts.",
    contribution: [
      "Directed a team of 6 artists on character design and visual assets.",
      "Built the scene and character editor in C#.",
      "Implemented a teacher dashboard and activity creation tools for classroom use.",
      "Established the art style and the production pipeline that kept it consistent.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/historias-para-armar/01-0.avif",
      alt: "Character builder screen from Historias Para Armar, its Spanish interface reading \"Elige un cuerpo para tu personaje\" above adult, teenager, child and objects options.",
      width: 1280,
      height: 720,
    },
    media: [
    ],
    visuals: { status: "public" },
    featured: true,
  },
  {
    slug: "peakmines",
    title: "Peakmines Art and Technical Direction",
    tagline: "Art direction, 2D and 3D production for an indie title.",
    metaDescription:
      "Art and technical direction on Peakmines at Inflextion Studios, with hands-on 2D and 3D production including the dwarf character set, all built in Unity.",
    client: "Peakmines",
    studio: "Inflextion Studios",
    year: "2021-2022",
    platform: "PC (Unity)",
    role: "Art Director & Unity Developer",
    disciplines: ["art-direction", "3d-art"],
    stack: ["Unity", "Blender", "Substance Painter", "Photoshop"],
    summary:
      "Art and technical direction on Peakmines, plus hands-on 2D and 3D production including the dwarf character set.",
    constraint:
      "Directing a multidisciplinary team while staying hands-on in production, and keeping the pipeline efficient enough for a small studio.",
    contribution: [
      "Set the art direction and established the asset pipeline.",
      "Modeled, unwrapped and textured the character set.",
      "Coordinated designers, developers and artists across the project lifecycle.",
    ],
    outcome: "Delivered.",
    cover: {
      kind: "image",
      src: "/work/peakmines/01-0.avif",
      alt: "Peakmines running in Unity, a mining result dialog reading \"Mining has been successful, you got 60 raw gold\" over the mines screen.",
      width: 2400,
      height: 1350,
    },
    media: [
      {
        kind: "image",
        src: "/work/peakmines/02-1.avif",
        alt: "Peakmines furnaces screen with a scroll-styled dialog confirming the minting of four furnaces for 20 peak.",
        width: 1600,
        height: 900,
      },
      {
        kind: "image",
        src: "/work/peakmines/03-2.avif",
        alt: "Peakmines marketplace inventory, a grid of rings, bracelets, earrings and necklaces with their prices.",
        width: 1600,
        height: 839,
      },
      {
        kind: "image",
        src: "/work/peakmines/04-dwarf-01.avif",
        alt: "Dwarf miner crouching, in a helmet with a lamp, a pipe in his mouth and a loaded tool belt.",
        width: 1080,
        height: 1080,
      },
      {
        kind: "image",
        src: "/work/peakmines/05-dwarf-02.avif",
        alt: "Bare-chested tattooed dwarf with a braided orange beard, hands on hips, against an orange backdrop.",
        width: 1080,
        height: 1080,
      },
      {
        kind: "image",
        src: "/work/peakmines/06-dwarf-02-alt.avif",
        alt: "The same tattooed dwarf framed closer, showing the arm tattoos and belt detail.",
        width: 1080,
        height: 748,
      },
      {
        kind: "image",
        src: "/work/peakmines/07-dwarf-03.avif",
        alt: "Female character seated on the ground in leather and cloth gear, against a blue backdrop.",
        width: 1080,
        height: 1080,
      },
      {
        kind: "video",
        src: "/work/peakmines/08-dwarves-turntable.mp4",
        alt: "Turntable of the Peakmines dwarf characters rotating in place, showing each model from every angle.",
        width: 1920,
        height: 1080,
      },
    ],
    visuals: { status: "public" },
    featured: false,
  },
  {
    slug: "ohbb-kart-tower-of-god",
    title: "Tower of God Kart Characters",
    tagline: "Rak, Baam and Ha-Yuri modeled, unwrapped and textured.",
    metaDescription:
      "Character modeling, UVs and texturing for Rak, Baam and Ha-Yuri in OHBB Kart, built to share a single kart rig and read clearly at mobile racing speed.",
    client: "Tower of God",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist",
    disciplines: ["3d-art"],
    stack: ["Blender", "Substance Painter", "Unity"],
    summary:
      "The Tower of God roster for OHBB Kart: modeling, UVs and textures for Rak, Baam and Ha-Yuri, taken from the licensor's model sheets through to game-ready assets.",
    constraint:
      "Three bodies that share nothing. Ha-Yuri is a slim human in a school uniform, Baam wears a floor-length coat, and Rak is a heavyset reptilian in armour. All three had to fit one kart rig and read at the same distance on a phone.",
    contribution: [
      "Modeled and unwrapped each character to the licensor's model sheets.",
      "Textured to match the source illustration style, holding the flat cel-shaded read under mobile lighting.",
      "Iterated proportions across several WIP passes against licensor feedback before locking the final silhouettes.",
      "Reconciled the three body types onto the shared kart rig without redoing the rig per character.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-kart-tower-of-god/01-character-wip.avif",
      alt: "Front and back T-pose views of Ha-Yuri in a white and red school uniform, with long black hair streaked red.",
      width: 2400,
      height: 1631,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/02-baam-final.avif",
        alt: "Baam in a long black coat lined with a red and white pattern, standing in a T-pose.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/03-wip.avif",
        alt: "Front T-pose of a character in a black and red racing jacket over dark trousers and red-trimmed boots.",
        width: 1600,
        height: 900,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/04-wip-2.avif",
        alt: "Back view of the same racing jacket character, showing the print across the shoulders.",
        width: 1600,
        height: 900,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/05-wip-9.avif",
        alt: "Rak in chibi proportions wearing a white and red racing jacket, front view.",
        width: 1600,
        height: 900,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/06-wip-10.avif",
        alt: "Rak turned slightly, showing the jacket branding along the sleeve.",
        width: 1600,
        height: 900,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/07-rak-final.avif",
        alt: "Three views of the finished Rak in red armour with a hooded cape, front, back and side.",
        width: 1600,
        height: 575,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-tower-of-god/08-tower-of-god-key-art.avif",
        alt: "Tower of God key art with the cast posed around their karts beneath the series logo.",
        width: 1280,
        height: 720,
      },
    ],
    visuals: { status: "public" },
    featured: false,
  },
  {
    slug: "ohbb-kart-characters",
    title: "OHBB Kart Original Characters",
    tagline: "Original character work outside the licensed roster.",
    metaDescription:
      "Original character art for OHBB Kart: modeling, UVs and texturing, built to sit alongside the licensed SpongeBob and Invader Zim roster without clashing.",
    client: "Oh Baby Games",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist",
    disciplines: ["3d-art"],
    stack: ["Blender", "Substance Painter", "ZBrush", "Unity"],
    summary:
      "Two original drivers built for OHBB Kart alongside the licensed roster: a kimono-wearing swordfighter in stylised anime proportions, and Chibben, a duck in a leather jacket, gas mask and twin blades. Modeling, UVs and textures on both.",
    constraint:
      "Original designs had to hold their own next to SpongeBob and Invader Zim without looking imported from a different game. Two very different silhouettes, one shared kart rig, one shared material language.",
    contribution: [
      "Modeled, unwrapped and textured both characters, from design through to game-ready asset.",
      "Matched the licensed roster's proportions, edge density and material response so the grid reads as one cast.",
      "Kept each silhouette distinct enough to identify from behind at racing distance.",
    ],
    outcome: "Shipped.",
    cover: {
      kind: "image",
      src: "/work/ohbb-kart-characters/01-0.avif",
      alt: "Original character in a pink floral kimono with a sword at her side, three-quarter T-pose.",
      width: 2400,
      height: 2203,
    },
    media: [
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/02-1.avif",
        alt: "Close-up of the same character's face and pink ponytail, showing the eye and hair shading.",
        width: 1600,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/03-2.avif",
        alt: "Front T-pose of the kimono character, full body.",
        width: 1241,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/04-3.avif",
        alt: "Back T-pose of the kimono character, showing the obi bow and the pattern across the back.",
        width: 1245,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/05-0.avif",
        alt: "Close-up of Chibben, a yellow duck character in a black leather jacket wearing a gas mask with round red lenses.",
        width: 1495,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/06-1.avif",
        alt: "Chibben from the front, twin blades crossed behind his back.",
        width: 1421,
        height: 1591,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/07-2.avif",
        alt: "Chibben in three-quarter view.",
        width: 1255,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/08-3.avif",
        alt: "Chibben in profile, showing the mask filter and the jacket collar.",
        width: 990,
        height: 1600,
      },
      {
        kind: "image",
        src: "/work/ohbb-kart-characters/09-4.avif",
        alt: "Chibben from behind, showing the print on the back of the jacket.",
        width: 1421,
        height: 1600,
      },
    ],
    visuals: { status: "public" },
    featured: false,
  },
  {
    slug: "tower-defense-props",
    title: "Tower Defense Prop Library",
    tagline: "A full prop library built for a tower defense prototype.",
    metaDescription:
      "A full prop library for a tower defense prototype at Oh Baby Games: towers, structures and set dressing, built as one kit for a fixed top-down camera.",
    client: "Oh Baby Games",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist",
    disciplines: ["3d-art"],
    stack: ["Blender", "Substance Painter", "Unity"],
    summary:
      "The tower library for a tower defense prototype, built as upgrade families rather than one-off props: a serpent tower across three tiers, cannons on wooden platforms, a dragon-head emplacement and an arcane orb tower, all sharing one base module.",
    constraint:
      "Everything is seen from a fixed top-down camera at small on-screen size. A tower has to be identifiable by silhouette and colour alone, and its upgrade tier has to be legible at a glance without a UI label.",
    contribution: [
      "Modeled, unwrapped and textured the tower set on a shared circular base module, so tiers swap without re-authoring the footprint.",
      "Designed each upgrade tier to escalate visually: the serpent gains frills and scale, the cannon gains barrels and plating.",
      "Held the kit to one material set and a common scale, so levels instance densely without extra draw calls.",
    ],
    outcome: "Prototype delivered.",
    cover: {
      kind: "image",
      src: "/work/tower-defense-props/01-0.avif",
      alt: "Snake tower at its first tier, a small purple hooded snake on a plain metal base.",
      width: 452,
      height: 809,
    },
    media: [
      {
        kind: "image",
        src: "/work/tower-defense-props/02-1.avif",
        alt: "Snake tower upgraded, larger with green frills and a decorated base.",
        width: 584,
        height: 985,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/03-10.avif",
        alt: "Red dragon head tower with golden horns and bared teeth, mounted on a gold-rimmed base.",
        width: 805,
        height: 941,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/04-11.avif",
        alt: "Cannon angled upward on a wooden platform with a metal rim.",
        width: 865,
        height: 1078,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/05-12.avif",
        alt: "Cannon with a spiked barrel mounted on a gold-rimmed wooden base.",
        width: 676,
        height: 828,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/06-13.avif",
        alt: "Construction site base with scaffolding, planks and tools scattered across the platform.",
        width: 736,
        height: 736,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/07-2.avif",
        alt: "Blue and purple snake tower at its highest tier, coiled with green fins.",
        width: 684,
        height: 1077,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/08-3-1.avif",
        alt: "Twin-barrel cannon on a dark metal base with wooden bracing.",
        width: 919,
        height: 885,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/09-3.avif",
        alt: "Mounted cannon with an animal face on the barrel, on a wooden platform.",
        width: 894,
        height: 709,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/10-4.avif",
        alt: "Cannon with a toothed muzzle on a wooden platform with an orange support arm.",
        width: 731,
        height: 968,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/11-5.avif",
        alt: "Larger cannon with a blue shark-like head and a wide muzzle.",
        width: 795,
        height: 1131,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/12-6.avif",
        alt: "Small blue crystal orb resting on a slim metal base.",
        width: 441,
        height: 787,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/13-7.avif",
        alt: "Magic tower with a glowing green orb suspended in a golden frame.",
        width: 600,
        height: 1177,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/14-8.avif",
        alt: "Barrel-shaped tower with dark red panels and a crown of metal spikes.",
        width: 661,
        height: 654,
      },
      {
        kind: "image",
        src: "/work/tower-defense-props/15-9.avif",
        alt: "Red dragon head tower seen from another angle, showing the horn detail.",
        width: 640,
        height: 774,
      },
    ],
    visuals: { status: "public" },
    featured: false,
  },
  {
    slug: "weapons-props",
    title: "Game-Ready Weapon Set",
    tagline: "Four game-ready weapons: pistol, shotgun, rifle, rocket launcher.",
    metaDescription:
      "Four game-ready sci-fi weapons modeled, unwrapped and PBR textured to a shared texel density, staying distinct at thumbnail size in a weapon-select UI.",
    client: "Oh Baby Games",
    studio: "Oh Baby Games",
    year: "2022-2025",
    platform: "Mobile (Unity)",
    role: "3D Artist",
    disciplines: ["3d-art"],
    stack: ["Blender", "Substance Painter"],
    summary:
      "Four game-ready sci-fi weapons: a shotgun, a pistol, a rifle and a rocket launcher, modeled, unwrapped and PBR textured to one shared texel density and material library.",
    constraint:
      "Four silhouettes that stay distinguishable at thumbnail size in a weapon-select UI, and still read as one armoury rather than four unrelated props.",
    contribution: [
      "Modeled and unwrapped each weapon to a common texel density, so no piece looks softer than its neighbour in the same UI.",
      "Built one shared PBR material library across the set: worn bronze and tan plating with a blue energy cell as the recurring accent.",
      "Kept the barrel and grip masses distinct per weapon, so each is recognisable in silhouette alone.",
    ],
    outcome: "Prototype delivered.",
    cover: {
      kind: "image",
      src: "/work/weapons-props/01-shotgun.avif",
      alt: "Game-ready sci-fi shotgun in tan and bronze, with a blue energy cell set into the receiver.",
      width: 1712,
      height: 561,
    },
    media: [
      {
        kind: "image",
        src: "/work/weapons-props/02-pistol.avif",
        alt: "Game-ready sci-fi pistol with a long blade-like slide and a glowing blue cylinder.",
        width: 1468,
        height: 551,
      },
      {
        kind: "image",
        src: "/work/weapons-props/03-rifle.avif",
        alt: "Game-ready sci-fi rifle with a slim profile, blue trim and an integrated scope.",
        width: 1600,
        height: 557,
      },
      {
        kind: "image",
        src: "/work/weapons-props/04-rocket-launcher.avif",
        alt: "Game-ready sci-fi rocket launcher with a wide tube, blue indicator strips and a metal muzzle.",
        width: 1575,
        height: 719,
      },
    ],
    visuals: { status: "public" },
    featured: false,
  },
];

export const featuredProjects = projects.filter((p) => p.featured && !p.draft);
export const publishedProjects = projects.filter((p) => !p.draft);

/**
 * The four projects that lead the home page, in order, chosen by hand.
 *
 * Deliberately not `featured.slice(0, 4)`. `featured` marks strong work and
 * drives sitemap priority; this is a separate editorial call about what should
 * carry the first screen. Chevrolet is strong but publishes no imagery, and a
 * "visuals withheld" card is a weak opening beat. The licensed IPs earn the
 * slots because they are recognisable and they have images.
 */
const HOME_SELECTION = [
  "mercedes-actros-vr",
  "cusutools",
  "ohbb-kart-spongebob",
  "ohbb-kart-invader-zim",
] as const;

export const homeProjects = HOME_SELECTION.map((slug) => {
  const project = publishedProjects.find((p) => p.slug === slug);
  if (!project) throw new Error(`HOME_SELECTION references unknown project: ${slug}`);
  return project;
});

/** Projects that can carry imagery. The rest are described in text only. */
export const illustratedProjects = publishedProjects.filter(
  (p) => p.visuals.status === "public" && p.cover,
);

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}
