import type { ReactNode } from "react";
import { cn } from "@/lib/utils";

/**
 * The frame a project under NDA renders in, on a card and on its own page.
 *
 * The panel used to be an empty bordered rectangle. Sitting in a grid beside
 * real captures, that reads as an image that failed to load rather than as a
 * decision someone made. The wireframe behind it states the actual situation:
 * there is geometry here and you are not being shown it.
 *
 * The mesh is generated by scripts/make-mesh.mjs and already carries its own
 * left-to-right fade, so the label and the reason keep a clean ground to sit
 * on. It is one cached file for the whole site rather than markup repeated per
 * card, and it costs no JavaScript.
 */
export function WithheldPanel({
  variant = "card",
  className,
  children,
}: {
  /** A card keeps a 16:10 box, a project page panel is close to 6:1. Each has its own mesh. */
  variant?: "card" | "wide";
  className?: string;
  children: ReactNode;
}) {
  return (
    <div className={cn("relative isolate overflow-hidden border border-line bg-surface", className)}>
      <span
        aria-hidden
        className={cn(
          "pointer-events-none absolute inset-0 -z-10 bg-cover bg-center bg-no-repeat",
          variant === "wide"
            ? "bg-[url('/mesh-withheld-wide.svg')]"
            : "bg-[url('/mesh-withheld.svg')]",
        )}
      />
      {children}
    </div>
  );
}
